export {
  loadVercelStableEnvironmentAuthority,
  VercelStableEnvironmentAuthorityError,
  type VercelStableEnvironmentAuthorityErrorEncoded,
  VercelStableEnvironmentAuthorityFailureReason,
  type VercelStableEnvironmentAuthorityFailureReasonEncoded,
  VercelStableEnvironmentAuthorityPath,
  type VercelStableEnvironmentAuthorityPathEncoded,
} from "./stable-environment-authority.js";
export {
  CreateVercelPreviewEnvironmentMetadata,
  type CreateVercelPreviewEnvironmentMetadataEncoded,
  DeleteVercelPreviewEnvironmentMetadata,
  type DeleteVercelPreviewEnvironmentMetadataEncoded,
  ObserveVercelPreviewEnvironmentMetadata,
  type ObserveVercelPreviewEnvironmentMetadataEncoded,
  ObserveVercelPreviewFeedback,
  type ObserveVercelPreviewFeedbackEncoded,
  SetVercelPreviewFeedback,
  type SetVercelPreviewFeedbackEncoded,
  VercelPreviewConfiguration,
  type VercelPreviewConfigurationShape,
  VercelPreviewConfigurationFailureReason,
  VercelPreviewConfigurationOperation,
  VercelPreviewConfigurationReadError,
  VercelPreviewConfigurationWriteError,
  VercelPreviewEnvironmentMetadataAttributes,
  type VercelPreviewEnvironmentMetadataAttributesEncoded,
  VercelPreviewEnvironmentMetadataObservation,
  type VercelPreviewEnvironmentMetadataObservationEncoded,
  VercelPreviewEnvironmentMetadataProps,
  type VercelPreviewEnvironmentMetadataPropsEncoded,
  VercelPreviewEnvironmentValue,
  type VercelPreviewEnvironmentValueEncoded,
  VercelPreviewFeedbackAttributes,
  type VercelPreviewFeedbackAttributesEncoded,
  VercelPreviewFeedbackObservation,
  type VercelPreviewFeedbackObservationEncoded,
  VercelPreviewFeedbackProps,
  type VercelPreviewFeedbackPropsEncoded,
  VercelPreviewFeedbackValue,
  type VercelPreviewFeedbackValueEncoded,
  VercelPreviewStage,
  type VercelPreviewStageEncoded,
} from "./configuration.js";
export {
  VercelPreviewConfigurationLive,
  type VercelPreviewConfigurationLiveRequirements,
} from "./configuration-live.layer.js";
export {
  emptyVercelPreviewConfigurationMemory,
  layerVercelPreviewConfigurationMemory,
  VercelPreviewConfigurationMemoryConfig,
  type VercelPreviewConfigurationMemoryConfigEncoded,
  VercelPreviewConfigurationMemoryControl,
  type VercelPreviewConfigurationMemoryControlShape,
  VercelPreviewConfigurationMemoryCount,
  VercelPreviewConfigurationMemoryFailureMode,
  type VercelPreviewConfigurationMemoryFailureModeEncoded,
  VercelPreviewFeedbackDrift,
} from "./configuration-memory.layer.js";
export {
  layerVercelPreviewConfigurationProviders,
  VercelPreviewEnvironmentMetadata,
  VercelPreviewFeedback,
} from "./configuration-providers.js";
export {
  loadVercelPreviewConfigurationInput,
  VercelPreviewConfigurationAuthorityError,
  type VercelPreviewConfigurationAuthorityErrorEncoded,
  VercelPreviewConfigurationAuthorityFailureReason,
  type VercelPreviewConfigurationAuthorityFailureReasonEncoded,
  VercelPreviewConfigurationAuthorityPath,
  type VercelPreviewConfigurationAuthorityPathEncoded,
  VercelPreviewConfigurationInput,
  type VercelPreviewConfigurationInputEncoded,
  VercelPreviewConfigurationPhase,
  type VercelPreviewConfigurationPhaseEncoded,
} from "./preview-configuration-authority.js";
export {
  layerVercelPreviewConfigurationLive,
  layerVercelPreviewConfigurationLiveProviders,
} from "./preview-configuration-live-providers.js";
export {
  VercelPreviewPhotonBindingValuesLive,
  VercelStableEnvironmentBindingsLive,
} from "./stable-environment-live.layer.js";
export {
  layerVercelStableEnvironmentMemory,
  VercelStableEnvironmentMemoryConfig,
  VercelStableEnvironmentMemoryFailureMode,
  VercelStableEnvironmentMemoryValue,
} from "./stable-environment-memory.layer.js";
export {
  previewPhotonSecretReference,
  productionPhotonSecretReference,
  ResolveVercelPreviewPhotonValue,
  type ResolveVercelPreviewPhotonValueEncoded,
  UpdateVercelStableEnvironmentVariable,
  type UpdateVercelStableEnvironmentVariableEncoded,
  VercelManagedEnvironmentValue,
  type VercelManagedEnvironmentValueEncoded,
  VercelPreviewPhotonBindingValues,
  VercelPreviewPhotonBindingValuesDenied,
  type VercelPreviewPhotonBindingValuesShape,
  VercelPreviewPhotonEnvironmentKey,
  type VercelPreviewPhotonEnvironmentKeyEncoded,
  VercelPreviewPhotonSecretOwner,
  VercelProductionPhotonSecretOwner,
  VercelStableEnvironmentBindings,
  VercelStableEnvironmentBindingsDenied,
  type VercelStableEnvironmentBindingsShape,
  VercelStableEnvironmentFailureReason,
  VercelStableEnvironmentOperation,
  VercelStableEnvironmentProviderFailure,
  VercelStableEnvironmentProviderStatus,
  VercelStableEnvironmentReadError,
  VercelStableEnvironmentValue,
  type VercelStableEnvironmentValueEncoded,
  VercelStableEnvironmentWriteError,
} from "./stable-environment.js";
export {
  VercelCredentialError,
  VercelDeploymentsReadError,
  VercelDomainsReadError,
  VercelEnvironmentVariablesReadError,
  VercelMarketplaceBindingsReadError,
  VercelProjectsReadError,
} from "./errors.js";
export {
  VercelCredentialsLive,
  VercelLive,
  VercelProjectCredentialsLive,
} from "./live.layer.js";
export {
  emptyVercelInventory,
  layerVercelMemory,
  VercelMemoryControl,
  type VercelMemoryControlShape,
} from "./memory.layer.js";
export {
  layerVercelReadOnlyProviders,
  VercelDeploymentObservationResource,
  VercelEnvironmentVariable,
  VercelMarketplaceBinding,
  VercelProject,
  VercelProjectDomain,
} from "./providers.js";
export {
  DiscoverVercelProject,
  type DiscoverVercelProjectEncoded,
  ListedVercelDeployments,
  type ListedVercelDeploymentsEncoded,
  ListedVercelEnvironmentVariables,
  type ListedVercelEnvironmentVariablesEncoded,
  ListedVercelMarketplaceBindings,
  type ListedVercelMarketplaceBindingsEncoded,
  ListedVercelProjectDomains,
  type ListedVercelProjectDomainsEncoded,
  ListedVercelProjects,
  type ListedVercelProjectsEncoded,
  ListVercelDeployments,
  type ListVercelDeploymentsEncoded,
  ListVercelEnvironmentVariables,
  type ListVercelEnvironmentVariablesEncoded,
  ListVercelMarketplaceBindings,
  type ListVercelMarketplaceBindingsEncoded,
  ListVercelProjectDomains,
  type ListVercelProjectDomainsEncoded,
  ListVercelProjects,
  type ListVercelProjectsEncoded,
  ObserveVercelDeployment,
  type ObserveVercelDeploymentEncoded,
  ObserveVercelEnvironmentVariable,
  type ObserveVercelEnvironmentVariableEncoded,
  ObserveVercelMarketplaceBinding,
  type ObserveVercelMarketplaceBindingEncoded,
  ObserveVercelProject,
  type ObserveVercelProjectEncoded,
  ObserveVercelProjectDomain,
  type ObserveVercelProjectDomainEncoded,
  VercelCanonicalDomain,
  type VercelCanonicalDomainEncoded,
  VercelAccessToken,
  type VercelAccessTokenEncoded,
  VercelCredentialFailureReason,
  type VercelCredentialFailureReasonEncoded,
  VercelCredentialScope,
  type VercelCredentialScopeEncoded,
  VercelDeploymentId,
  type VercelDeploymentIdEncoded,
  VercelDeploymentObservation,
  type VercelDeploymentObservationEncoded,
  VercelDeploymentObservationAttributes,
  type VercelDeploymentObservationAttributesEncoded,
  VercelDeploymentObservationProps,
  type VercelDeploymentObservationPropsEncoded,
  VercelDeploymentStatus,
  type VercelDeploymentStatusEncoded,
  VercelDeploymentTarget,
  type VercelDeploymentTargetEncoded,
  VercelEnvironmentTarget,
  type VercelEnvironmentTargetEncoded,
  VercelEnvironmentVariableAttributes,
  type VercelEnvironmentVariableAttributesEncoded,
  VercelEnvironmentVariableDesiredState,
  type VercelEnvironmentVariableDesiredStateEncoded,
  VercelEnvironmentVariableId,
  type VercelEnvironmentVariableIdEncoded,
  VercelEnvironmentVariableKey,
  type VercelEnvironmentVariableKeyEncoded,
  VercelEnvironmentVariableObservation,
  type VercelEnvironmentVariableObservationEncoded,
  VercelEnvironmentVariableProps,
  type VercelEnvironmentVariablePropsEncoded,
  VercelEnvironmentVariableType,
  type VercelEnvironmentVariableTypeEncoded,
  VercelEnvironmentVariableUpdatedAt,
  type VercelEnvironmentVariableUpdatedAtEncoded,
  VercelGitBranch,
  type VercelGitBranchEncoded,
  VercelGitSha,
  type VercelGitShaEncoded,
  VercelIntegrationConfigurationId,
  type VercelIntegrationConfigurationIdEncoded,
  VercelIntegrationId,
  type VercelIntegrationIdEncoded,
  VercelInventoryProjectScope,
  type VercelInventoryProjectScopeEncoded,
  VercelInventoryScope,
  type VercelInventoryScopeEncoded,
  VercelMarketplaceBindingAttributes,
  type VercelMarketplaceBindingAttributesEncoded,
  VercelMarketplaceBindingObservation,
  type VercelMarketplaceBindingObservationEncoded,
  VercelMarketplaceBindingProps,
  type VercelMarketplaceBindingPropsEncoded,
  VercelMarketplaceDatabaseId,
  type VercelMarketplaceDatabaseIdEncoded,
  VercelMarketplaceResourceId,
  type VercelMarketplaceResourceIdEncoded,
  VercelPaginationCursor,
  type VercelPaginationCursorEncoded,
  VercelProjectAttributes,
  type VercelProjectAttributesEncoded,
  VercelProjectDomainAttributes,
  type VercelProjectDomainAttributesEncoded,
  VercelProjectDomainObservation,
  type VercelProjectDomainObservationEncoded,
  VercelProjectDomainProps,
  type VercelProjectDomainPropsEncoded,
  VercelProjectDiscovery,
  type VercelProjectDiscoveryEncoded,
  VercelProjectFramework,
  type VercelProjectFrameworkEncoded,
  VercelProjectId,
  type VercelProjectIdEncoded,
  VercelProjectName,
  type VercelProjectNameEncoded,
  VercelProjectObservation,
  type VercelProjectObservationEncoded,
  VercelProjectProps,
  type VercelProjectPropsEncoded,
  VercelProviderRate,
  type VercelProviderRateEncoded,
  VercelProjectsPage,
  type VercelProjectsPageEncoded,
  VercelReadFailureReason,
  type VercelReadFailureReasonEncoded,
  VercelReadOnlyInventory,
  type VercelReadOnlyInventoryEncoded,
  VercelReadOperation,
  type VercelReadOperationEncoded,
  VercelTeamId,
  type VercelTeamIdEncoded,
} from "./schemas.js";
export {
  VercelCredentials,
  type VercelCredentialsShape,
  VercelDeployments,
  type VercelDeploymentsShape,
  VercelDomains,
  type VercelDomainsShape,
  VercelEnvironmentVariables,
  type VercelEnvironmentVariablesShape,
  VercelMarketplaceBindings,
  type VercelMarketplaceBindingsShape,
  VercelProjects,
  type VercelProjectsShape,
} from "./services.js";
export {
  AutomaticProductionBlockedReceipt,
  type AutomaticProductionBlockedReceipt as AutomaticProductionBlockedReceiptType,
  AutomaticProductionBlockedReceiptJson,
  AutomaticProductionFailureCategory,
  ProductionDeploymentError,
  ProductionDeploymentFailureReason,
  ProductionDeploymentOperation,
} from "./production.errors.js";
export {
  makeProductionDeploymentsMemory,
  ProductionDeploymentMemoryControl,
  type ProductionDeploymentMemoryInput,
  type ProductionDeploymentMemorySnapshot,
  ProductionMemoryFailure,
} from "./production-memory.layer.js";
export {
  ProductionDeploymentConfigLive,
  ProductionDeploymentConfigService,
  ProductionDeploymentsLive,
} from "./production.live.layer.js";
export {
  AutomaticProductionReceipt,
  type AutomaticProductionReceipt as AutomaticProductionReceiptType,
  AutomaticProductionReceiptJson,
  AutomaticProductionStatus,
  InspectProductionDeployment,
  ProductionDeployment,
  type ProductionDeployment as ProductionDeploymentType,
  ProductionDeploymentUrl,
  ProductionProject,
  ProductionProxyHealth,
  StageProductionDeployment,
} from "./production.schemas.js";
export {
  ProductionDeployments,
  type ProductionDeploymentsShape,
} from "./production.service.js";
export { runAutomaticProduction } from "./production.js";
