export {
  SecretOwner,
  type SecretOwnerEncoded,
  SecretOwnership,
  type SecretOwnershipEncoded,
  SecretReference,
  type SecretReferenceEncoded,
  SecretReferenceId,
  type SecretReferenceIdEncoded,
  SecretRevision,
  type SecretRevisionEncoded,
} from "./secret-reference.js";
export {
  AdoptionManifest,
  type AdoptionManifestEncoded,
  AdoptionManifestJson,
  type AdoptionManifestJsonEncoded,
  AdoptionManifestResource,
  type AdoptionManifestResourceEncoded,
} from "./adoption-manifest.js";
export { loadInfrastructureCommandConfig } from "./config.js";
export {
  canonicalizeInfrastructureObservedManifest,
  InfrastructureInventory,
  InfrastructureInventoryArtifact,
  type InfrastructureInventoryArtifactEncoded,
  InfrastructureInventoryArtifactJson,
  InfrastructureInventoryDigest,
  type InfrastructureInventoryDigestEncoded,
  InfrastructureInventoryLive,
  InfrastructureInventoryPrincipalFingerprint,
  type InfrastructureInventoryPrincipalFingerprintEncoded,
  InfrastructureInventoryReadError,
  InfrastructureInventoryReadMessage,
  type InfrastructureInventoryReadMessageEncoded,
  InfrastructureInventorySourceSha,
  type InfrastructureInventorySourceShaEncoded,
  InfrastructureInventoryTarget,
  type InfrastructureInventoryTargetEncoded,
  InfrastructureObservedManifest,
  type InfrastructureObservedManifestEncoded,
  PhotonInventoryProjectObservation,
  type PhotonInventoryProjectObservationEncoded,
  PhotonReadOnlyInventory,
  type PhotonReadOnlyInventoryEncoded,
} from "./inventory.js";
export {
  SyntheticResourceDeleteError,
  SyntheticResourceReadError,
  SyntheticResourceWriteError,
} from "./errors.js";
export {
  SyntheticProviderCredential,
  type SyntheticProviderCredentialEncoded,
  SyntheticProviderCredentials,
  SyntheticProviderCredentialsLive,
} from "./live.layer.js";
export {
  emptyMemoryConfig,
  layerMemory,
  SyntheticMemoryConfig,
  type SyntheticMemoryConfigEncoded,
  SyntheticMemoryDrift,
  type SyntheticMemoryDriftEncoded,
  SyntheticMemoryFailureMode,
  type SyntheticMemoryFailureModeEncoded,
  SyntheticMemoryWriteCount,
  type SyntheticMemoryWriteCountEncoded,
  SyntheticResourcesMemoryControl,
  type SyntheticResourcesMemoryControlShape,
} from "./memory.layer.js";
export { SyntheticResource, SyntheticResourceProvider } from "./providers.js";
export {
  InfrastructureArtifactDigest,
  type InfrastructureArtifactDigestEncoded,
  InfrastructureBoundedReceipt,
  type InfrastructureBoundedReceiptEncoded,
  InfrastructureBoundedReceiptJson,
  type InfrastructureBoundedReceiptJsonEncoded,
  InfrastructureDetailArtifact,
  type InfrastructureDetailArtifactEncoded,
  InfrastructureReceiptStatus,
  type InfrastructureReceiptStatusEncoded,
} from "./receipt.js";
export {
  AdoptionManifestDigest,
  type AdoptionManifestDigestEncoded,
  AlchemyLogicalResourceId,
  type AlchemyLogicalResourceIdEncoded,
  DeletedSyntheticResource,
  type DeletedSyntheticResourceEncoded,
  DeleteSyntheticResource,
  type DeleteSyntheticResourceEncoded,
  InfrastructureCommandInput,
  type InfrastructureCommandInputEncoded,
  InfrastructureDestructivePolicy,
  type InfrastructureDestructivePolicyEncoded,
  InfrastructureDiffClass,
  type InfrastructureDiffClassEncoded,
  InfrastructureLifecycleOperation,
  type InfrastructureLifecycleOperationEncoded,
  InfrastructureManifestPath,
  type InfrastructureManifestPathEncoded,
  InfrastructureMode,
  type InfrastructureModeEncoded,
  InfrastructureOutcomeCertainty,
  type InfrastructureOutcomeCertaintyEncoded,
  InfrastructureOwnershipState,
  type InfrastructureOwnershipStateEncoded,
  InfrastructureProvider,
  type InfrastructureProviderEncoded,
  InfrastructureRemovalPolicy,
  type InfrastructureRemovalPolicyEncoded,
  InfrastructureResourceKind,
  type InfrastructureResourceKindEncoded,
  InfrastructureRetryClass,
  type InfrastructureRetryClassEncoded,
  InfrastructureStackName,
  type InfrastructureStackNameEncoded,
  InfrastructureStage,
  type InfrastructureStageEncoded,
  InfrastructureStateRevision,
  type InfrastructureStateRevisionEncoded,
  ListedSyntheticResources,
  type ListedSyntheticResourcesEncoded,
  ListSyntheticResources,
  type ListSyntheticResourcesEncoded,
  ObserveSyntheticResource,
  type ObserveSyntheticResourceEncoded,
  PreviewInfrastructureStateRevision,
  type PreviewInfrastructureStateRevisionEncoded,
  ProductionInfrastructureStateRevision,
  type ProductionInfrastructureStateRevisionEncoded,
  ReconciledSyntheticResource,
  type ReconciledSyntheticResourceEncoded,
  ReconcileSyntheticResource,
  type ReconcileSyntheticResourceEncoded,
  SyntheticDesiredValue,
  type SyntheticDesiredValueEncoded,
  SyntheticPhysicalResourceId,
  type SyntheticPhysicalResourceIdEncoded,
  SyntheticResourceAttributes,
  type SyntheticResourceAttributesEncoded,
  SyntheticResourceObservation,
  type SyntheticResourceObservationEncoded,
  SyntheticResourceProps,
  type SyntheticResourcePropsEncoded,
  VercelDeploymentId,
  type VercelDeploymentIdEncoded,
  VercelProjectId,
  type VercelProjectIdEncoded,
} from "./schemas.js";
export { SyntheticResources, type SyntheticResourcesShape } from "./service.js";
