export type BoundaryKind =
  | "cli"
  | "config"
  | "file"
  | "framework"
  | "http-in"
  | "http-out"
  | "persistence"
  | "provider";

export type BoundaryException = Readonly<{
  file: string;
  symbol: string;
  occurrence: string;
  owner: string;
  boundaryKind: BoundaryKind;
  canonicalContract: string;
  admittedSyntax: string;
  reason: string;
  rule: BoundaryRule;
}>;

export type BoundaryRule =
  | "boundary-raw-primitive"
  | "inline-string-schema"
  | "codec-provenance"
  | "raw-outbound-write"
  | "config-primitive"
  | "direct-json"
  | "raw-fetch"
  | "raw-response-text"
  | "sync-schema-codec"
  | "unsafe-boundary-syntax";

/**
 * Exact temporary admissions for already-classified adapters. These entries
 * are migration work, not a count baseline. Removing or changing the named
 * syntax makes the entry stale and fails check:boundaries.
 */
export const boundaryExceptions = [
  {
    file: "apps/agent/agent/config.ts",
    symbol: "AgentModelProviderConfigError",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "AgentModelProviderConfig",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 must replace the tagged-error raw fields with checked diagnostic schemas.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/config.ts",
    symbol: "AgentModelProviderConfigError",
    occurrence: "StringKeyword:string#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "AgentModelProviderConfig",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 must replace the tagged-error raw fields with checked diagnostic schemas.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/config.ts",
    symbol: "codexProxyInternalTokenConfig",
    occurrence: "Config.redacted:BUNDJIL_CODEX_PROXY_INTERNAL_TOKEN#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "AgentModelProviderConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the app token config migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/executor/config.ts",
    symbol: "ExecutorConnectionConfigError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "ExecutorConnectionConfigError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/executor/config.ts",
    symbol: "ExecutorConnectionConfigError",
    occurrence: "PropertyAssignment:reason: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "ExecutorConnectionConfigError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/channel.service.ts",
    symbol: "SendblueChannelShape",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueCompletedMessage",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 owns the Sendblue framework callback and delivery contract migration.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/channel.service.ts",
    symbol: "SendblueChannelShape",
    occurrence: "UnknownKeyword:unknown#2",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueCompletedMessage",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 owns the Sendblue framework callback and delivery contract migration.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/channel.service.ts",
    symbol: "body",
    occurrence: "request.text#1",
    owner: "apps/agent",
    boundaryKind: "http-in",
    canonicalContract: "SendblueInboundMessage",
    admittedSyntax: "raw Response text or JSON reader",
    reason:
      "Task 3 must decode the named webhook request codec at this adapter.",
    rule: "raw-response-text",
  },
  {
    file: "apps/agent/agent/lib/sendblue/channel.service.ts",
    symbol: "dispatchAcceptedInbound",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueCompletedMessage",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 owns the Sendblue framework callback and delivery contract migration.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/channel.service.ts",
    symbol: "deliverCompletedMessage",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueCompletedMessage",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 owns the Sendblue framework callback and delivery contract migration.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/channel.service.ts",
    symbol: "deliverCompletedMessage",
    occurrence: "StringKeyword:string#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueCompletedMessage",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 owns the Sendblue framework callback and delivery contract migration.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "apiKeyConfig",
    occurrence: "Config.redacted:BUNDJIL_SENDBLUE_API_KEY#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "apiSecretConfig",
    occurrence: "Config.redacted:BUNDJIL_SENDBLUE_API_SECRET#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "webhookSecretConfig",
    occurrence: "Config.redacted:BUNDJIL_SENDBLUE_WEBHOOK_SECRET#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "routingKeyConfig",
    occurrence: "Config.redacted:BUNDJIL_SENDBLUE_ROUTING_KEY#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "senderIdentitiesConfig",
    occurrence: "Config.redacted:BUNDJIL_SENDBLUE_SENDER_IDENTITIES#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "replayStoreUrlConfig",
    occurrence: "Config.redacted:BUNDJIL_SENDBLUE_REPLAY_STORE_URL#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "replayStoreUrlConfig",
    occurrence: "Config.redacted:KV_REST_API_URL#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "replayStoreTokenConfig",
    occurrence: "Config.redacted:BUNDJIL_SENDBLUE_REPLAY_STORE_TOKEN#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "replayStoreTokenConfig",
    occurrence: "Config.redacted:KV_REST_API_TOKEN#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "replayStorePrefixConfig",
    occurrence: "Config.nonEmptyString:BUNDJIL_SENDBLUE_REPLAY_STORE_PREFIX#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/config-error.ts",
    symbol: "SendblueConfigError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueConfigError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/delivery-uncertain-error.ts",
    symbol: "SendblueDeliveryUncertainError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueDeliveryUncertainError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/replay-store-error.ts",
    symbol: "SendblueReplayStoreError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueReplayStoreError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/request-error.ts",
    symbol: "SendblueRequestError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueRequestError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/response-error.ts",
    symbol: "SendblueResponseError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueResponseError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/routing-error.ts",
    symbol: "SendblueRoutingError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueRoutingError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/sender-not-allowed-error.ts",
    symbol: "SendblueSenderNotAllowedError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueSenderNotAllowedError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/webhook-authentication-error.ts",
    symbol: "SendblueWebhookAuthenticationError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueWebhookAuthenticationError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/webhook-schema-error.ts",
    symbol: "SendblueWebhookSchemaError",
    occurrence: "PropertyAssignment:boundary: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueWebhookSchemaError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/webhook-schema-error.ts",
    symbol: "SendblueWebhookSchemaError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueWebhookSchemaError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/session-router.service.ts",
    symbol: "keyedSendblueDigest",
    occurrence: "StringKeyword:string#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueConversationKey",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason: "Task 3 owns the framework session-key projection migration.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/production-preflight.ts",
    symbol: "ProductionPreflightError",
    occurrence: "StringKeyword:string#1",
    owner: "apps/agent",
    boundaryKind: "cli",
    canonicalContract: "ProductionPreflightEvidence",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 owns checked operator diagnostics for production preflight.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/scripts/production-preflight.ts",
    symbol: "snapshotPath",
    occurrence: "Config.nonEmptyString:BUNDJIL_PRODUCTION_PREFLIGHT_SNAPSHOT#1",
    owner: "apps/agent",
    boundaryKind: "cli",
    canonicalContract: "ProductionPreflightEvidence",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the operator-script config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/codex-proxy/scripts/prove-preview.ts",
    symbol: "internalTokenConfig",
    occurrence: "Config.redacted:BUNDJIL_CODEX_PROXY_INTERNAL_TOKEN#1",
    owner: "apps/codex-proxy",
    boundaryKind: "cli",
    canonicalContract: "PreviewProofContract",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns Preview proof config schemas.",
    rule: "config-primitive",
  },
  {
    file: "apps/codex-proxy/scripts/prove-preview.ts",
    symbol: "protectionBypassConfig",
    occurrence: "Config.redacted:BUNDJIL_CODEX_PROXY_VERCEL_BYPASS#1",
    owner: "apps/codex-proxy",
    boundaryKind: "cli",
    canonicalContract: "PreviewProofContract",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns Preview proof config schemas.",
    rule: "config-primitive",
  },
  {
    file: "apps/codex-proxy/scripts/prove-preview.ts",
    symbol: "previewProofRequest",
    occurrence: "Schema.encodeSync#1",
    owner: "apps/codex-proxy",
    boundaryKind: "cli",
    canonicalContract: "PreviewProofContract",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 3 must keep proof encoding inside an Effect program.",
    rule: "sync-schema-codec",
  },
  {
    file: "apps/codex-proxy/scripts/prove-preview.ts",
    symbol: "previewProofRequest",
    occurrence: "Schema.decodeUnknownSync#1",
    owner: "apps/codex-proxy",
    boundaryKind: "cli",
    canonicalContract: "PreviewProofContract",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 3 must keep proof encoding inside an Effect program.",
    rule: "sync-schema-codec",
  },
  {
    file: "apps/codex-proxy/scripts/prove-preview.ts",
    symbol: "encodePreviewProofSuccess",
    occurrence: "Schema.encodeSync#1",
    owner: "apps/codex-proxy",
    boundaryKind: "cli",
    canonicalContract: "PreviewProofContract",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 3 must keep proof encoding inside an Effect program.",
    rule: "sync-schema-codec",
  },
  {
    file: "apps/codex-proxy/scripts/prove-preview.ts",
    symbol: "encodePreviewProofBlocked",
    occurrence: "Schema.encodeSync#1",
    owner: "apps/codex-proxy",
    boundaryKind: "cli",
    canonicalContract: "PreviewProofContract",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 3 must keep proof encoding inside an Effect program.",
    rule: "sync-schema-codec",
  },
  {
    file: "apps/codex-proxy/scripts/prove-preview.ts",
    symbol: "fetchResponse",
    occurrence: "fetch#1",
    owner: "apps/codex-proxy",
    boundaryKind: "http-out",
    canonicalContract: "PreviewProofContract",
    admittedSyntax: "global fetch call",
    reason: "Task 3 owns the proof HTTP client migration.",
    rule: "raw-fetch",
  },
  {
    file: "apps/codex-proxy/scripts/prove-preview.ts",
    symbol: "responseText",
    occurrence: "response.text#1",
    owner: "apps/codex-proxy",
    boundaryKind: "http-in",
    canonicalContract: "PreviewProofContract",
    admittedSyntax: "raw Response text or JSON reader",
    reason:
      "Task 3 must decode the proof response through its canonical codec.",
    rule: "raw-response-text",
  },
  {
    file: "apps/codex-proxy/scripts/smoke-test.ts",
    symbol: "encodeChatCompletionRequest",
    occurrence: "Schema.encodeUnknownSync#1",
    owner: "apps/codex-proxy",
    boundaryKind: "cli",
    canonicalContract: "OpenAICompatibleChatCompletionRequest",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 3 must keep smoke-test codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "apps/codex-proxy/scripts/smoke-test.ts",
    symbol: "encodeSmokeTestResult",
    occurrence: "Schema.encodeSync#1",
    owner: "apps/codex-proxy",
    boundaryKind: "cli",
    canonicalContract: "OpenAICompatibleChatCompletionRequest",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 3 must keep smoke-test codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "apps/codex-proxy/scripts/smoke-test.ts",
    symbol: "health",
    occurrence: "fetch#1",
    owner: "apps/codex-proxy",
    boundaryKind: "http-out",
    canonicalContract: "OpenAICompatibleChatCompletionRequest",
    admittedSyntax: "global fetch call",
    reason: "Task 3 owns the smoke-test HTTP client migration.",
    rule: "raw-fetch",
  },
  {
    file: "apps/codex-proxy/scripts/smoke-test.ts",
    symbol: "stream",
    occurrence: "fetch#1",
    owner: "apps/codex-proxy",
    boundaryKind: "http-out",
    canonicalContract: "OpenAICompatibleChatCompletionRequest",
    admittedSyntax: "global fetch call",
    reason: "Task 3 owns the smoke-test HTTP client migration.",
    rule: "raw-fetch",
  },
  {
    file: "apps/codex-proxy/scripts/smoke-test.ts",
    symbol: "body",
    occurrence: "stream.text#1",
    owner: "apps/codex-proxy",
    boundaryKind: "http-in",
    canonicalContract: "OpenAICompatibleChatCompletionRequest",
    admittedSyntax: "raw Response text or JSON reader",
    reason: "Task 3 must decode the smoke response at this adapter.",
    rule: "raw-response-text",
  },
  {
    file: "apps/codex-proxy/src/env.ts",
    symbol: "internalTokenConfig",
    occurrence: "Config.redacted:BUNDJIL_CODEX_PROXY_INTERNAL_TOKEN#1",
    owner: "apps/codex-proxy",
    boundaryKind: "config",
    canonicalContract: "CodexProxyRuntimeConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the proxy config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/codex-proxy/src/env.ts",
    symbol: "accountIdConfig",
    occurrence: "Config.redacted:BUNDJIL_CODEX_ACCOUNT_ID#1",
    owner: "apps/codex-proxy",
    boundaryKind: "config",
    canonicalContract: "CodexProxyRuntimeConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the proxy config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/codex-proxy/src/env.ts",
    symbol: "vercelRuntimeMarkerConfig",
    occurrence: "Config.nonEmptyString:VERCEL#1",
    owner: "apps/codex-proxy",
    boundaryKind: "config",
    canonicalContract: "CodexProxyRuntimeConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the proxy config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/codex-proxy/src/env.ts",
    symbol: "makeCodexProxyConfig",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "apps/codex-proxy",
    boundaryKind: "config",
    canonicalContract: "CodexProxyRuntimeConfig",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason: "Task 3 owns the proxy runtime config boundary migration.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/codex-proxy/src/proof-cipher-config.layer.ts",
    symbol: "proofCipherKeyConfig",
    occurrence: "Config.redacted:BUNDJIL_CODEX_PROOF_PROFILE_ENCRYPTION_KEY#1",
    owner: "apps/codex-proxy",
    boundaryKind: "config",
    canonicalContract: "CodexProxyProofCipherConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns proof-cipher config schemas.",
    rule: "config-primitive",
  },
  {
    file: "apps/codex-proxy/src/proof-cipher-config.layer.ts",
    symbol: "proofCipherKeyIdConfig",
    occurrence:
      "Config.nonEmptyString:BUNDJIL_CODEX_PROOF_PROFILE_ENCRYPTION_KEY_ID#1",
    owner: "apps/codex-proxy",
    boundaryKind: "config",
    canonicalContract: "CodexProxyProofCipherConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns proof-cipher config schemas.",
    rule: "config-primitive",
  },
  {
    file: "packages/codex-oauth/scripts/import-local-profile-filesystem.ts",
    symbol: "localProfileStoreDirectoryConfig",
    occurrence: "Config.nonEmptyString:BUNDJIL_CODEX_LOCAL_PROFILE_STORE_DIR#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexLocalProfileImport",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 2 owns local filesystem import config schemas.",
    rule: "config-primitive",
  },
  {
    file: "packages/codex-oauth/scripts/import-local-profile-filesystem.ts",
    symbol: "encodeImportSuccessOutput",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexLocalProfileImport",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator output codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/import-local-profile-filesystem.ts",
    symbol: "encodeImportBlockedOutput",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexLocalProfileImport",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator output codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/import-local-profile.ts",
    symbol: "encodeImportSuccessOutput",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexLocalProfileImport",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator output codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/import-local-profile.ts",
    symbol: "encodeImportBlockedOutput",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexLocalProfileImport",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator output codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/login-subscription.ts",
    symbol: "encodeLoginSuccessOutput",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexSubscriptionLogin",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator output codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/login-subscription.ts",
    symbol: "encodeLoginBlockedOutput",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexSubscriptionLogin",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator output codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/probe-empty-namespace.ts",
    symbol: "encodeNamespaceProbeOutput",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexNamespaceProbe",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator output codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/probe-empty-namespace.ts",
    symbol: "encodeNamespaceProbeBlockedOutput",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexNamespaceProbe",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator output codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/prove-codex-responses.ts",
    symbol: "encodeProofSuccessOutput",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexResponsesProof",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator output codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/prove-codex-responses.ts",
    symbol: "encodeProofBlockedOutput",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexResponsesProof",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator output codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/prove-hosted-staged-refresh.ts",
    symbol: "internalTokenConfig",
    occurrence: "Config.redacted:BUNDJIL_CODEX_PROXY_INTERNAL_TOKEN#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexHostedRefreshProof",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 2 owns hosted proof config schemas.",
    rule: "config-primitive",
  },
  {
    file: "packages/codex-oauth/scripts/prove-hosted-staged-refresh.ts",
    symbol: "requestBody",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexHostedRefreshProof",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator proof codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/prove-hosted-staged-refresh.ts",
    symbol: "requestBody",
    occurrence: "Schema.decodeUnknownSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexHostedRefreshProof",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator proof codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/prove-hosted-staged-refresh.ts",
    symbol: "encodeProofSuccess",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexHostedRefreshProof",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator proof codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/prove-hosted-staged-refresh.ts",
    symbol: "encodeProofBlocked",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexHostedRefreshProof",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator proof codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/prove-hosted-staged-refresh.ts",
    symbol: "fetchResponse",
    occurrence: "fetch#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "http-out",
    canonicalContract: "CodexHostedRefreshProof",
    admittedSyntax: "global fetch call",
    reason: "Task 2 owns hosted proof HTTP migration.",
    rule: "raw-fetch",
  },
  {
    file: "packages/codex-oauth/scripts/prove-hosted-staged-refresh.ts",
    symbol: "readResponse",
    occurrence: "response.text#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "http-in",
    canonicalContract: "CodexHostedRefreshProof",
    admittedSyntax: "raw Response text or JSON reader",
    reason: "Task 2 must decode the hosted proof response through its codec.",
    rule: "raw-response-text",
  },
  {
    file: "packages/codex-oauth/scripts/prove-stored-profile.ts",
    symbol: "encodeProofSuccessOutput",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexStoredProfileProof",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator output codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/prove-stored-profile.ts",
    symbol: "encodeProofBlockedOutput",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexStoredProfileProof",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator output codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/stage-near-expiry-profile.ts",
    symbol: "encodeStageSuccess",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexNearExpiryProfileStage",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator output codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/scripts/stage-near-expiry-profile.ts",
    symbol: "encodeStageBlocked",
    occurrence: "Schema.encodeSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexNearExpiryProfileStage",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must make operator output codecs Effectful.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/src/browser-launcher.service.ts",
    symbol: "makeCodexBrowserCommand",
    occurrence: "StringKeyword:string#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "cli",
    canonicalContract: "CodexBrowserLauncher",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason: "Task 2 owns the browser command adapter contract.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/codex-oauth/src/codex-http-client.service.ts",
    symbol: "body",
    occurrence: "response.text#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "provider",
    canonicalContract: "CodexResponsesProofResult",
    admittedSyntax: "raw Response text or JSON reader",
    reason:
      "Task 2 must decode the provider text body through the response codec.",
    rule: "raw-response-text",
  },
  {
    file: "packages/codex-oauth/src/codex-http-client.service.ts",
    symbol: "body",
    occurrence: "response.text#2",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "provider",
    canonicalContract: "CodexResponsesProofResult",
    admittedSyntax: "raw Response text or JSON reader",
    reason:
      "Task 2 must decode the provider text body through the response codec.",
    rule: "raw-response-text",
  },
  {
    file: "packages/codex-oauth/src/codex-responses.config.ts",
    symbol: "proofAccessTokenConfig",
    occurrence: "Config.redacted:CODEX_ACCESS_TOKEN#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "config",
    canonicalContract: "CodexResponsesProofInput",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 2 owns the Codex proof credential config schema.",
    rule: "config-primitive",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-http-network-error.ts",
    symbol: "CodexHttpNetworkError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexHttpNetworkError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-http-status-error.ts",
    symbol: "CodexHttpStatusError",
    occurrence: "PropertyAssignment:statusText: Schema.String#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexHttpStatusError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-http-status-error.ts",
    symbol: "CodexHttpStatusError",
    occurrence: "PropertyAssignment:contentType: Schema.String#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexHttpStatusError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-http-status-error.ts",
    symbol: "CodexHttpStatusError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexHttpStatusError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-local-profile-import-error.ts",
    symbol: "CodexLocalProfileImportError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexLocalProfileImportError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-oauth-auth-temporarily-unavailable.ts",
    symbol: "CodexOAuthAuthTemporarilyUnavailable",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexOAuthAuthTemporarilyUnavailable",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-oauth-profile-cipher-error.ts",
    symbol: "CodexOAuthProfileCipherError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexOAuthProfileCipherError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-oauth-profile-commit-conflict.ts",
    symbol: "CodexOAuthProfileCommitConflict",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexOAuthProfileCommitConflict",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-oauth-profile-commit-error.ts",
    symbol: "CodexOAuthProfileCommitError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexOAuthProfileCommitError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-oauth-reauthentication-required.ts",
    symbol: "CodexOAuthReauthenticationRequired",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexOAuthReauthenticationRequired",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-oauth-refresh-lock-error.ts",
    symbol: "CodexOAuthRefreshLockError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexOAuthRefreshLockError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-oauth-token-expired.ts",
    symbol: "CodexOAuthTokenExpired",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexOAuthTokenExpired",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-oauth-token-missing.ts",
    symbol: "CodexOAuthTokenMissing",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexOAuthTokenMissing",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-oauth-token-provider-error.ts",
    symbol: "CodexOAuthTokenProviderError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexOAuthTokenProviderError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-oauth-unsupported-runtime-path.ts",
    symbol: "CodexOAuthUnsupportedRuntimePath",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexOAuthUnsupportedRuntimePath",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-responses-request-error.ts",
    symbol: "CodexResponsesRequestError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexResponsesRequestError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-responses-stream-error.ts",
    symbol: "CodexResponsesStreamError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexResponsesStreamError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/codex-subscription-auth-error.ts",
    symbol: "CodexSubscriptionAuthError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexSubscriptionAuthError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/oauth-profile-not-found.ts",
    symbol: "OAuthProfileNotFound",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "OAuthProfileNotFound",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/oauth-profile-schema-error.ts",
    symbol: "OAuthProfileSchemaError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "OAuthProfileSchemaError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/oauth-profile-storage-error.ts",
    symbol: "OAuthProfileStorageError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "OAuthProfileStorageError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/openai-compatible-proxy-auth-error.ts",
    symbol: "OpenAICompatibleProxyAuthError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "OpenAICompatibleProxyAuthError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/openai-compatible-proxy-request-error.ts",
    symbol: "OpenAICompatibleProxyRequestError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "OpenAICompatibleProxyRequestError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/errors/upstash-key-value-store-config-error.ts",
    symbol: "UpstashKeyValueStoreConfigError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "UpstashKeyValueStoreConfigError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/filesystem-key-value-store.layer.ts",
    symbol: "CodexFileSystemKeyValueStoreLive",
    occurrence: "StringKeyword:string#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "file",
    canonicalContract: "CodexFileSystemKeyValueStore",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason: "Task 2 owns the filesystem persistence adapter contract.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/codex-oauth/src/local-auth-cache-source.service.ts",
    symbol: "content",
    occurrence: "call#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "http-in",
    canonicalContract: "content",
    admittedSyntax: "raw Response text or JSON reader",
    reason: "Task 2 owns this exact raw-response-text migration.",
    rule: "raw-response-text",
  },
  {
    file: "packages/codex-oauth/src/local-auth-cache-source.service.ts",
    symbol: "CodexLocalAuthCacheSourceMemory",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "file",
    canonicalContract: "CodexCliAuthCache",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason: "Task 2 owns the local cache source contract.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/codex-oauth/src/local-profile-import.config.ts",
    symbol: "homeDirectoryConfig",
    occurrence: "Config.nonEmptyString:HOME#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "config",
    canonicalContract: "CodexLocalProfileImportConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 2 owns the local profile import config schema.",
    rule: "config-primitive",
  },
  {
    file: "packages/codex-oauth/src/loopback-callback.service.ts",
    symbol: "CodexLoopbackCallbackSession",
    occurrence: "StringKeyword:string#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexOAuthAuthorizationCallback",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason: "Task 2 owns the loopback callback framework adapter.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/codex-oauth/src/loopback-callback.service.ts",
    symbol: "decodeCodexOAuthCallbackRequest",
    occurrence: "StringKeyword:string#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexOAuthAuthorizationCallback",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason: "Task 2 owns the loopback callback framework adapter.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/codex-oauth/src/loopback-callback.service.ts",
    symbol: "decodeCodexOAuthCallbackRequest",
    occurrence: "StringKeyword:string#2",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexOAuthAuthorizationCallback",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason: "Task 2 owns the loopback callback framework adapter.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/codex-oauth/src/loopback-callback.service.ts",
    symbol: "decodeCodexOAuthCallbackRequest",
    occurrence: "StringKeyword:string#3",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexOAuthAuthorizationCallback",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason: "Task 2 owns the loopback callback framework adapter.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/codex-oauth/src/loopback-callback.service.ts",
    symbol: "CodexLoopbackCallbackMemoryOptions",
    occurrence: "StringKeyword:string#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "framework",
    canonicalContract: "CodexOAuthAuthorizationCallback",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason: "Task 2 owns the loopback callback framework adapter.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/codex-oauth/src/mock.layer.ts",
    symbol: "state",
    occurrence: "Schema.decodeUnknownSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "persistence",
    canonicalContract: "CodexOAuthObserverSnapshot",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must replace the mock-layer synchronous fixture codec.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/src/observer.service.ts",
    symbol: "emptySnapshot",
    occurrence: "Schema.decodeUnknownSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "persistence",
    canonicalContract: "CodexOAuthObserverSnapshot",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 must construct this snapshot through an Effectful codec.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/src/refresh-lock.service.ts",
    symbol: "defaultCodexOAuthRefreshLockTtlMillis",
    occurrence: "Schema.decodeUnknownSync#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "persistence",
    canonicalContract: "CodexOAuthRefreshLock",
    admittedSyntax: "synchronous Effect Schema codec",
    reason: "Task 2 owns the refresh-lock codec migration.",
    rule: "sync-schema-codec",
  },
  {
    file: "packages/codex-oauth/src/schemas.ts",
    symbol: "CodexOAuthProviderErrorResponse",
    occurrence: "PropertyAssignment:error: Schema.NonEmptyString#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "provider",
    canonicalContract: "CodexOAuthProviderErrorResponse",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 2 owns the provider error diagnostic field migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/codex-oauth/src/subscription-auth-protocol.service.ts",
    symbol: "buildCodexOAuthAuthorizationSession",
    occurrence: "StringKeyword:string#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "provider",
    canonicalContract: "CodexOAuthAuthorizationSession",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason: "Task 2 owns the subscription protocol adapter contract.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/codex-oauth/src/subscription-auth-protocol.service.ts",
    symbol: "createCodexOAuthAuthorizationSession",
    occurrence: "StringKeyword:string#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "provider",
    canonicalContract: "CodexOAuthAuthorizationSession",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason: "Task 2 owns the subscription protocol adapter contract.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/codex-oauth/src/upstash-persistence.layer.ts",
    symbol: "upstashRestTokenConfig",
    occurrence: "Config.redacted:UPSTASH_REDIS_REST_TOKEN#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "config",
    canonicalContract: "UpstashRedisConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 2 owns the persistence config schema.",
    rule: "config-primitive",
  },
  {
    file: "packages/codex-oauth/src/upstash-persistence.layer.ts",
    symbol: "upstashRestTokenConfig",
    occurrence: "Config.redacted:KV_REST_API_TOKEN#1",
    owner: "@bundjil/codex-oauth",
    boundaryKind: "config",
    canonicalContract: "UpstashRedisConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 2 owns the persistence config schema.",
    rule: "config-primitive",
  },
  {
    file: "packages/effect-persistence/src/errors.ts",
    symbol: "AtomicKeyValueStoreError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "AtomicKeyValueStoreError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#1",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#2",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#3",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "UnknownKeyword:unknown#2",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#4",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "UnknownKeyword:unknown#3",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#5",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#6",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "UnknownKeyword:unknown#4",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#7",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#8",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#9",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "UnknownKeyword:unknown#5",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/eve-effect/src/errors/gateway-config-error.ts",
    symbol: "BundjilAgentGatewayConfigError",
    occurrence: "PropertyAssignment:setting: Schema.NonEmptyString#1",
    owner: "@bundjil/eve-effect",
    boundaryKind: "framework",
    canonicalContract: "BundjilAgentGatewayConfigError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/eve-effect/src/errors/gateway-config-error.ts",
    symbol: "BundjilAgentGatewayConfigError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/eve-effect",
    boundaryKind: "framework",
    canonicalContract: "BundjilAgentGatewayConfigError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/eve-effect/src/errors/operation-error.ts",
    symbol: "BundjilAgentOperationError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/eve-effect",
    boundaryKind: "framework",
    canonicalContract: "BundjilAgentOperationError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/eve-effect/src/errors/schema-error.ts",
    symbol: "BundjilAgentSchemaError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/eve-effect",
    boundaryKind: "framework",
    canonicalContract: "BundjilAgentSchemaError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/eve-effect/src/eve/tool-adapter.ts",
    symbol: "EveSchema",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "@bundjil/eve-effect",
    boundaryKind: "framework",
    canonicalContract: "toEveSchema",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Eve's Standard Schema bridge requires unknown at the framework adapter; Task 4 will retain only the unavoidable generic constraint.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/eve-effect/src/eve/tool-adapter.ts",
    symbol: "toEveSchema",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "@bundjil/eve-effect",
    boundaryKind: "framework",
    canonicalContract: "toEveSchema",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Eve's Standard Schema bridge requires unknown at the framework adapter; Task 4 will retain only the unavoidable generic constraint.",
    rule: "boundary-raw-primitive",
  },
] as const satisfies readonly BoundaryException[];
