export type BoundaryKind =
  | "cli"
  | "config"
  | "file"
  | "framework"
  | "http-in"
  | "http-out"
  | "persistence"
  | "provider";

export type BoundaryException = Readonly<{
  file: string;
  symbol: string;
  occurrence: string;
  owner: string;
  boundaryKind: BoundaryKind;
  canonicalContract: string;
  admittedSyntax: string;
  reason: string;
  rule: BoundaryRule;
}>;

export type BoundaryRule =
  | "boundary-raw-primitive"
  | "inline-string-schema"
  | "codec-provenance"
  | "raw-outbound-write"
  | "config-primitive"
  | "direct-json"
  | "raw-fetch"
  | "raw-response-text"
  | "sync-schema-codec"
  | "unsafe-boundary-syntax";

/**
 * Exact temporary admissions for already-classified adapters. These entries
 * are migration work, not a count baseline. Removing or changing the named
 * syntax makes the entry stale and fails check:boundaries.
 */
export const boundaryExceptions = [
  {
    file: "apps/agent/agent/config.ts",
    symbol: "AgentModelProviderConfigError",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "AgentModelProviderConfig",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 must replace the tagged-error raw fields with checked diagnostic schemas.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/config.ts",
    symbol: "AgentModelProviderConfigError",
    occurrence: "StringKeyword:string#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "AgentModelProviderConfig",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 must replace the tagged-error raw fields with checked diagnostic schemas.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/config.ts",
    symbol: "codexProxyInternalTokenConfig",
    occurrence: "Config.redacted:BUNDJIL_CODEX_PROXY_INTERNAL_TOKEN#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "AgentModelProviderConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the app token config migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/executor/config.ts",
    symbol: "ExecutorConnectionConfigError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "ExecutorConnectionConfigError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/executor/config.ts",
    symbol: "ExecutorConnectionConfigError",
    occurrence: "PropertyAssignment:reason: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "ExecutorConnectionConfigError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/channel.service.ts",
    symbol: "SendblueChannelShape",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueCompletedMessage",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 owns the Sendblue framework callback and delivery contract migration.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/channel.service.ts",
    symbol: "SendblueChannelShape",
    occurrence: "UnknownKeyword:unknown#2",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueCompletedMessage",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 owns the Sendblue framework callback and delivery contract migration.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/channel.service.ts",
    symbol: "body",
    occurrence: "request.text#1",
    owner: "apps/agent",
    boundaryKind: "http-in",
    canonicalContract: "SendblueInboundMessage",
    admittedSyntax: "raw Response text or JSON reader",
    reason:
      "Task 3 must decode the named webhook request codec at this adapter.",
    rule: "raw-response-text",
  },
  {
    file: "apps/agent/agent/lib/sendblue/channel.service.ts",
    symbol: "dispatchAcceptedInbound",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueCompletedMessage",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 owns the Sendblue framework callback and delivery contract migration.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/channel.service.ts",
    symbol: "deliverCompletedMessage",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueCompletedMessage",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 owns the Sendblue framework callback and delivery contract migration.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/channel.service.ts",
    symbol: "deliverCompletedMessage",
    occurrence: "StringKeyword:string#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueCompletedMessage",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 owns the Sendblue framework callback and delivery contract migration.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "apiKeyConfig",
    occurrence: "Config.redacted:BUNDJIL_SENDBLUE_API_KEY#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "apiSecretConfig",
    occurrence: "Config.redacted:BUNDJIL_SENDBLUE_API_SECRET#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "webhookSecretConfig",
    occurrence: "Config.redacted:BUNDJIL_SENDBLUE_WEBHOOK_SECRET#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "routingKeyConfig",
    occurrence: "Config.redacted:BUNDJIL_SENDBLUE_ROUTING_KEY#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "senderIdentitiesConfig",
    occurrence: "Config.redacted:BUNDJIL_SENDBLUE_SENDER_IDENTITIES#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "replayStoreUrlConfig",
    occurrence: "Config.redacted:BUNDJIL_SENDBLUE_REPLAY_STORE_URL#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "replayStoreUrlConfig",
    occurrence: "Config.redacted:KV_REST_API_URL#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "replayStoreTokenConfig",
    occurrence: "Config.redacted:BUNDJIL_SENDBLUE_REPLAY_STORE_TOKEN#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "replayStoreTokenConfig",
    occurrence: "Config.redacted:KV_REST_API_TOKEN#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/config.ts",
    symbol: "replayStorePrefixConfig",
    occurrence: "Config.nonEmptyString:BUNDJIL_SENDBLUE_REPLAY_STORE_PREFIX#1",
    owner: "apps/agent",
    boundaryKind: "config",
    canonicalContract: "SendblueConfig",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the Sendblue config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/config-error.ts",
    symbol: "SendblueConfigError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueConfigError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/delivery-uncertain-error.ts",
    symbol: "SendblueDeliveryUncertainError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueDeliveryUncertainError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/replay-store-error.ts",
    symbol: "SendblueReplayStoreError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueReplayStoreError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/request-error.ts",
    symbol: "SendblueRequestError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueRequestError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/response-error.ts",
    symbol: "SendblueResponseError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueResponseError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/routing-error.ts",
    symbol: "SendblueRoutingError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueRoutingError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/sender-not-allowed-error.ts",
    symbol: "SendblueSenderNotAllowedError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueSenderNotAllowedError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/webhook-authentication-error.ts",
    symbol: "SendblueWebhookAuthenticationError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueWebhookAuthenticationError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/webhook-schema-error.ts",
    symbol: "SendblueWebhookSchemaError",
    occurrence: "PropertyAssignment:boundary: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueWebhookSchemaError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/errors/webhook-schema-error.ts",
    symbol: "SendblueWebhookSchemaError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueWebhookSchemaError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "apps/agent/agent/lib/sendblue/session-router.service.ts",
    symbol: "keyedSendblueDigest",
    occurrence: "StringKeyword:string#1",
    owner: "apps/agent",
    boundaryKind: "framework",
    canonicalContract: "SendblueConversationKey",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason: "Task 3 owns the framework session-key projection migration.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/agent/production-preflight.ts",
    symbol: "ProductionPreflightError",
    occurrence: "StringKeyword:string#1",
    owner: "apps/agent",
    boundaryKind: "cli",
    canonicalContract: "ProductionPreflightEvidence",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Task 3 owns checked operator diagnostics for production preflight.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "apps/agent/scripts/production-preflight.ts",
    symbol: "snapshotPath",
    occurrence: "Config.nonEmptyString:BUNDJIL_PRODUCTION_PREFLIGHT_SNAPSHOT#1",
    owner: "apps/agent",
    boundaryKind: "cli",
    canonicalContract: "ProductionPreflightEvidence",
    admittedSyntax: "primitive Effect Config constructor",
    reason: "Task 3 owns the operator-script config Schema migration.",
    rule: "config-primitive",
  },
  {
    file: "apps/codex-proxy/src/env.ts",
    symbol: "makeCodexProxyConfig",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "apps/codex-proxy",
    boundaryKind: "config",
    canonicalContract: "CodexProxyRuntimeConfig",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason: "Task 3 owns the proxy runtime config boundary migration.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/errors.ts",
    symbol: "AtomicKeyValueStoreError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "AtomicKeyValueStoreError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#1",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#2",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#3",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "UnknownKeyword:unknown#2",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#4",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "UnknownKeyword:unknown#3",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#5",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#6",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "UnknownKeyword:unknown#4",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#7",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#8",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "StringKeyword:string#9",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/effect-persistence/src/upstash-client.internal.ts",
    symbol: "UpstashPersistenceClient",
    occurrence: "UnknownKeyword:unknown#5",
    owner: "@bundjil/effect-persistence",
    boundaryKind: "persistence",
    canonicalContract: "UpstashPersistenceClient",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Native Upstash SDK primitives are private until Task 3 decodes command responses at this facade.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/eve-effect/src/errors/gateway-config-error.ts",
    symbol: "BundjilAgentGatewayConfigError",
    occurrence: "PropertyAssignment:setting: Schema.NonEmptyString#1",
    owner: "@bundjil/eve-effect",
    boundaryKind: "framework",
    canonicalContract: "BundjilAgentGatewayConfigError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/eve-effect/src/errors/gateway-config-error.ts",
    symbol: "BundjilAgentGatewayConfigError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/eve-effect",
    boundaryKind: "framework",
    canonicalContract: "BundjilAgentGatewayConfigError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/eve-effect/src/errors/operation-error.ts",
    symbol: "BundjilAgentOperationError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/eve-effect",
    boundaryKind: "framework",
    canonicalContract: "BundjilAgentOperationError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/eve-effect/src/errors/schema-error.ts",
    symbol: "BundjilAgentSchemaError",
    occurrence: "PropertyAssignment:message: Schema.NonEmptyString#1",
    owner: "@bundjil/eve-effect",
    boundaryKind: "framework",
    canonicalContract: "BundjilAgentSchemaError",
    admittedSyntax: "inline Schema.String or Schema.NonEmptyString field",
    reason: "Task 3 owns this exact inline-string-schema migration.",
    rule: "inline-string-schema",
  },
  {
    file: "packages/eve-effect/src/eve/tool-adapter.ts",
    symbol: "EveSchema",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "@bundjil/eve-effect",
    boundaryKind: "framework",
    canonicalContract: "toEveSchema",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Eve's Standard Schema bridge requires unknown at the framework adapter; Task 4 will retain only the unavoidable generic constraint.",
    rule: "boundary-raw-primitive",
  },
  {
    file: "packages/eve-effect/src/eve/tool-adapter.ts",
    symbol: "toEveSchema",
    occurrence: "UnknownKeyword:unknown#1",
    owner: "@bundjil/eve-effect",
    boundaryKind: "framework",
    canonicalContract: "toEveSchema",
    admittedSyntax: "raw primitive in the named external adapter contract",
    reason:
      "Eve's Standard Schema bridge requires unknown at the framework adapter; Task 4 will retain only the unavoidable generic constraint.",
    rule: "boundary-raw-primitive",
  },
] as const satisfies readonly BoundaryException[];
